# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- publish: $(System.DefaultWorkingDirectory)/bin/web
  artifact: WebApp

- script: |
    npm install --only=dev
    npm run build
  displayName: 'npm install and build'
  
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/output'
    Contents: '**\*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/outpout'
    CleanTargetFolder: true
  
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'node app.js'
    failOnStderr: true

